// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnoqGljxbuok_WaM0e2oLmf8gYr96dmUU',
    appId: '1:363335774443:web:fdaf28486ddd2949bf0eae',
    messagingSenderId: '363335774443',
    projectId: 'naipaybackend',
    authDomain: 'naipaybackend.firebaseapp.com',
    storageBucket: 'naipaybackend.firebasestorage.app',
    measurementId: 'G-2L4LVNRS18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRZDyB_SYwAdjV0PTi2_1alx0jeWaGv9A',
    appId: '1:363335774443:android:4660027aa4db3dfabf0eae',
    messagingSenderId: '363335774443',
    projectId: 'naipaybackend',
    storageBucket: 'naipaybackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxMyhOe_zpDog0sCRABmVI2HntH5-7Fdk',
    appId: '1:363335774443:ios:345a60a22e20333ebf0eae',
    messagingSenderId: '363335774443',
    projectId: 'naipaybackend',
    storageBucket: 'naipaybackend.firebasestorage.app',
    iosBundleId: 'com.example.naipay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxMyhOe_zpDog0sCRABmVI2HntH5-7Fdk',
    appId: '1:363335774443:ios:345a60a22e20333ebf0eae',
    messagingSenderId: '363335774443',
    projectId: 'naipaybackend',
    storageBucket: 'naipaybackend.firebasestorage.app',
    iosBundleId: 'com.example.naipay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnoqGljxbuok_WaM0e2oLmf8gYr96dmUU',
    appId: '1:363335774443:web:c16919ea65c73356bf0eae',
    messagingSenderId: '363335774443',
    projectId: 'naipaybackend',
    authDomain: 'naipaybackend.firebaseapp.com',
    storageBucket: 'naipaybackend.firebasestorage.app',
    measurementId: 'G-2MG38DW8Y5',
  );
}
